---

- name: DHCP_CONFIG
  hosts: router
  gather_facts: false
  connection: local
  tasks:
    - name: TELNET
      telnet:
        user: admin
        password: pass
        login_prompt: "Username: "
        prompts:
          - '[>|#]'
        command:
          - terminal length 0
          - enable
          - config t
          - ip dhcp excluded-add 10.1.1.1 10.1.1.150
          - ip dhcp Excluded-add 10._.10.1 10._.10.100
          - ip dhcp pool vlanone
          - network 10.1.1.0 255.255.255.0
          - default-router 10.1.1.1
          - domain-name encor.com
          - dns-server 8.8.8.8
          - option 150 ip 10.1.1.1
          - ip dhcp pool WIFIDATA
          - network 10._.10.0 255.255.255.0
          - default-router 10._.10.4
          - domain-name WIFIDATA.COM
          - dns-server 10._.1.10
          - option 150 ip 10._.10.4
